name: CI - S3 Service

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "applications/s3-service/**"

  workflow_dispatch:   # ✅ manual run button
    inputs:
      run_type:
        description: "manual CI run"
        required: false
        default: "manual"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: applications/s3-service
        run: pip install -r requirements.txt

      - name: Import test
        working-directory: applications/s3-service
        run: python -c "import flask, boto3; print('S3 CI OK')"
